name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  job-ci:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

#    - name: golangci-lint
#      uses: golangci/golangci-lint-action@v3
#      with:
#        version: v1.29

    - name: Build
      run: go build -v ./...

    - name: Run Gosec Security Scanner
      uses: securego/gosec@master
      with:
        args: ./...

    - name: Test
      run: go test -v ./...

#  job-cd:
